import { polygonContains } from 'd3';
import type { SegmentationPolygon } from 'dive-common/apispec';
import { readFileSync } from 'fs';
import {
  SegmentationMaxPolygonAreaError,
  SegmentationMaxPolygonPoints,
  SegmentationMaxPolygonPointsLimit,
} from './constants';
import {
  maskGeometry, maskKeypoints, maskSeeds, consistentMaskSeeds, maskArea,
} from './maskGeometry';

const desktopSeeds: { polygon: SegmentationPolygon; expected: [number, number][] }[] = JSON.parse(readFileSync(new URL('./desktopSeeds.json', import.meta.url), 'utf8'));

it('keeps disjoint components and holes, with full-resolution RLE', () => {
  const mask = new Uint8Array(30 * 20);
  for (let y = 2; y < 18; y += 1) {
    for (let x = 2; x < 28; x += 1) {
      if ((x < 15 || x > 20) && !(x > 5 && x < 10 && y > 5 && y < 12)) mask[y * 30 + x] = 1;
    }
  }
  const result = maskGeometry(mask, 30, 20);
  expect(result.success).toBe(true);
  expect(result.polygons).toHaveLength(2);
  expect(result.polygons!.flatMap((p) => p.holes)).toHaveLength(1);
  expect(result.maskShape).toEqual([20, 30]);
  expect(result.rleMask!.flatMap(([value, count]) => Array(count).fill(value))).toEqual([...mask]);
  const seeds = maskSeeds(result.polygons!);
  expect(seeds.length).toBeGreaterThan(1);
  seeds.forEach((point) => expect(result.polygons!.some((p) => polygonContains(p.exterior, point)
    && !p.holes.some((hole) => polygonContains(hole, point)))).toBe(true));
});

it('derives hull-extremes head/tail across all components and clips to their boundaries', () => {
  const a = { exterior: [[0, 0], [10, 0], [10, 4], [0, 4]] as [number, number][], holes: [] };
  const b = { exterior: [[15, 0], [20, 0], [20, 4], [15, 4]] as [number, number][], holes: [] };
  expect(maskKeypoints([a, b])).toEqual({ success: true, head: [20, 2], tail: [0, 2] });
});

describe('polygon vertex budget', () => {
  const size = 400;
  const draw = (inside: (x: number, y: number) => boolean) => {
    const mask = new Uint8Array(size * size);
    for (let y = 0; y < size; y += 1) {
      for (let x = 0; x < size; x += 1) if (inside(x - size / 2, y - size / 2)) mask[y * size + x] = 1;
    }
    return mask;
  };
  const disk = draw((x, y) => Math.hypot(x, y) < 150);
  const star = draw((x, y) => Math.hypot(x, y) < 110 + 70 * Math.cos(16 * Math.atan2(y, x)));
  const ring = draw((x, y) => Math.hypot(x, y) < 150 && Math.hypot(x, y) > 60);

  it('keeps every ring within the desktop maximum', () => {
    [disk, star, ring].forEach((mask) => {
      const { polygons } = maskGeometry(mask, size, size);
      polygons!.flatMap((p) => [p.exterior, ...p.holes]).forEach((points) => {
        expect(points.length).toBeLessThanOrEqual(SegmentationMaxPolygonPoints);
        expect(points.length).toBeGreaterThanOrEqual(4);
        expect(points[0]).toEqual(points[points.length - 1]);
      });
    });
    expect(maskGeometry(ring, size, size).polygons![0].holes).toHaveLength(1);
  });

  it('keeps the area of a simple outline', () => {
    const area = maskArea(maskGeometry(disk, size, size).polygons!);
    expect(Math.abs(area - Math.PI * 150 ** 2) / (Math.PI * 150 ** 2)).toBeLessThan(
      SegmentationMaxPolygonAreaError,
    );
  });

  it('grows the budget for a point-click mask too complex for it, up to the limit', () => {
    expect(maskGeometry(disk, size, size, true).polygons![0].exterior.length).toBeLessThanOrEqual(
      SegmentationMaxPolygonPoints,
    );
    const points = maskGeometry(star, size, size, true).polygons![0].exterior;
    expect(points.length).toBeGreaterThan(SegmentationMaxPolygonPoints);
    expect(points.length).toBeLessThanOrEqual(SegmentationMaxPolygonPointsLimit);
  });
});

it('returns a failure for an empty mask rather than an infinite bounding box', () => {
  expect(maskGeometry(new Uint8Array(100), 10, 10).success).toBe(false);
});

// Expected values generated by VIAME InteractiveStereo._interior_points using
// OpenCV, including a concave outline, hole, thin object and half-pixel vertices.
it.each(desktopSeeds)('matches desktop interior seed selection %#', ({ polygon, expected }) => {
  expect(maskSeeds([polygon as SegmentationPolygon])).toEqual(expected);
});

it('rejects per-component offset outliers and ignores failed correspondences', () => {
  const polygon = desktopSeeds[0].polygon as SegmentationPolygon;
  expect(consistentMaskSeeds(
    [[0, 0], [2, 0], [4, 0], [6, 0], [8, 0]],
    [[-10, 0], [-8, 0], [-6, 0], [40, 0], null],
    polygon,
  )).toEqual([[-10, 0], [-8, 0], [-6, 0]]);
});

it('measures mask area including disjoint components and subtracting holes', () => {
  expect(maskArea([desktopSeeds[0].polygon, desktopSeeds[1].polygon] as SegmentationPolygon[])).toBe(1000);
});
