name: Electron Build and Docs Deployment
on:
  release:
    types: [published]

jobs:
  platform_release:
    defaults:
      run:
        working-directory: client
    name: Build all packages for multiple platforms
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: windows-latest
          - os: macos-latest
          - os: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # "ref" specifies the branch to check out.
        # "github.event.release.target_commitish" is a global variable and specifies the branch the release targeted
        ref: ${{ github.event.release.target_commitish }}
    - name: Use Node 24
      uses: actions/setup-node@v3
      with:
        node-version: '24.15.0'
        cache: npm
        cache-dependency-path: client/package-lock.json
    - run: npm ci
    - run: npm run lint
    - name: Unit tests
      run: npm test
      if: ${{ matrix.config.os != 'windows-latest' }}

    - run: npm run build:electron

    # push the version changes to GitHub
    - name: Upload Release Asset
      uses: alexellis/upload-assets@0.2.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_paths: '["./client/dist_electron/DIVE-Desktop*"]'

  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # "ref" specifies the branch to check out.
        # "github.event.release.target_commitish" is a global variable and specifies the branch the release targeted
        ref: ${{ github.event.release.target_commitish }}

    # Deploy docs
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_FILE: mkdocs.yml
        EXTRA_PACKAGES: build-base
